DROP DATABASE IF EXISTS `Banking`;

CREATE DATABASE `Banking`;
USE `Banking`;

CREATE TABLE IF NOT EXISTS `USERS` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `iban` VARCHAR(7) NOT NULL UNIQUE,
    `active` TINYINT(1) NOT NULL DEFAULT '1',
    `type` ENUM('Public','Entreprise','Admin') NOT NULL DEFAULT 'Public',
    `email` VARCHAR(50) NOT NULL UNIQUE,
    `password` VARCHAR(80) NOT NULL,
    `money` DOUBLE NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS `TRANSACTIONS` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `date` DATETIME NOT NULL,
    `amount` DOUBLE NOT NULL,
    `reason` LONGTEXT NOT NULL,
    `idReceiver` INT NOT NULL,
    `idSender` INT NOT NULL
);

ALTER TABLE `TRANSACTIONS`
ADD FOREIGN KEY (idReceiver)
REFERENCES `USERS`(id);

ALTER TABLE `TRANSACTIONS`
ADD FOREIGN KEY (idSender)
REFERENCES `USERS`(id);